spring:
  application:
    name: eureka-service

server:
  port: 8443
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8443/eureka
